### PR TITLE
Issue #194: Change --args to match 'gdb --args'. 'cmd' now only takes program name.

### PR DESCRIPTION
**Pull request by fritzr**
Here is a patch which does what I think is reasonable: causes --args to take all remaining arguments as program arguments as with 'gdb --args'. The 'cmd' argument only takes the program name now. There are three options for 'cmd':

 1. Leave 'cmd' as nargs='*'; then any flags passed as '-' are ambiguous with gdbgui arguments unless the entire command string is qutoed, in which case it might as well be nargs=1. (i.e. `gdbgui [gdbgui-args] cmd [these-are-more-gdbgui-args]`)
 1. Set 'cmd' as nargs=1; this essentially works the same as above, but shows this explicitly in the usage string. Then to pass a full command string you would either do `gdgbui 'quoted-command --with-arguments' [gdbgui-args...]`.
 1. Set 'cmd' as nargs=`argparse.REMAINDER`; in this case the first non-option argument would begin debug program arguments. This acts more like non-GNU option parsing, i.e. `gdbgui [gdbgui-options] cmd-name [cmd-arguments...]`. However, with '--args' already set to `argparse.REMAINDER`, the two are equivalent. And then it is possible confusing if you want to do something like `gdbgui cmd-name --no-browser`, because `--no-browser` would be interpreted as a command arg.

For this reason I chose the second option. It is still convenient to debug simply with `gdbgui [gdbgui-args...] program` but you have gdb-like control with `gdbgui --args program [program-args...]`.

### CODE REVIEW

**Comment by cs01** [comment]
First, thanks for putting so much work and detail into this.

I am on board with #2. I tested it and it worked with `--args` but it failed when I tried the "cmd" option:
```
>> gdbgui/backend.py examples/c/hello_c.a
Opening gdbgui in browser at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
Traceback (most recent call last):
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/engineio/server.py", line 411, in _trigger_event
    return self.handlers[event](*args)
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/socketio/server.py", line 518, in _handle_eio_message
    self._handle_connect(sid, pkt.namespace)
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/socketio/server.py", line 421, in _handle_connect
    self.environ[sid]) is False:
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/Users/cs/.virtualenvs/gdbgui2/lib/python3.6/site-packages/flask_socketio/__init__.py", line 632, in _handle_event
    ret = handler()
  File "gdbgui/backend.py", line 324, in client_connected
    payload = _state.connect_client(request.sid, desired_gdbpid)
  File "/Users/cs/git/gdbgui/gdbgui/statemanager.py", line 58, in connect_client
    ) + REQUIRED_GDB_FLAGS
TypeError: must be str, not list
```

It is easily fixable by changing 

```
cmd = args.cmd
```
to 
```
cmd = [args.cmd]
```

in backend.py.

When viewing the help text I think the arguments should be ordered either from most commonly used/useful to least commonly. I think cmd and --args are the most useful. What do you think? Probably also makes sense to put cmd before --args so the help text doesn't show anything after `--args`.

Can the arg help text be changed to this?

> Specify the executable file and any arguments. All arguments are taken literally, so if used, this must be the last argument passed to gdbgui. Example: gdbgui [...] --args ./mybinary myarg -flag1 -flag2


Might be worth considering using [`dest`](https://docs.python.org/3/library/argparse.html#dest) and [mutual exclusion](https://docs.python.org/3/library/argparse.html#mutual-exclusion) since we can't have `cmd` and `--args` at the same time and they overload to the same variable in the end.

**Comment by fritzr** [comment]
I had considered using mutex groups, but I found the usage turns out like this:

```
usage: backend.py [-h] [-x GDB_CMD_FILE] [-g GDB] [--rr] [-p PORT]
                  [--host HOST] [-r] [--auth-file AUTH_FILE] [--user USER]
                  [--password PASSWORD] [--key KEY] [--cert CERT]
                  [--license LICENSE] [--project PROJECT] [-v]
                  [--hide_gdbgui_upgrades] [-n] [-b BROWSER] [--debug]
                  [--args ...]
                  [cmd]

A server that provides a graphical user interface to the gnu debugger (gdb).
https://github.com/cs01/gdbgui

positional arguments:
  cmd                   Name of the binary to run in gdb. To pass flags to the
                        binary, use --args instead. Example: gdbgui ./mybinary
                        [gdbgui-args...]

optional arguments:
  -h, --help            show this help message and exit
  --args ...            All remaining args are taken as the binary and
                        arguments to run in gdb (as with gdb --args). Example:
                        gdbgui [...] --args ./mybinary myarg -flag1 -flag2
gdb commands:
[...]
```

In which case `--args` or `cmd` are not shown under `gdb commands` section; nor are they shown with a mutex pipe as I would expect (i.e. `[--args ...|cmd]`). The latter is likely because `cmd` is a positional argument whereas `--args` is an optional argument. I believe it is for the same reason that `--args` shows up before `cmd` in the list, even though `--args` is set to `argparse.REMAINDER`. (That could be considered a deficiency in argparse because `argparse.REMAINDER` options should always occur last, even after positional arguments... oh well.)

However, it does accomplish placing both `cmd` and `--args` at the top of the usage like we want (I agree that makes sense) and it saves us having to check the mutex condition ourselves.

I also realized I could fix 'cmd' from str->list using `type=`.

**Comment by fritzr** [comment]
Oh yeah, and this one fixes the `--args` text to match your request.

**Comment by cs01** [comment]
> I also realized I could fix 'cmd' from str->list using type=.

Nice!

**Comment by vcunat** [comment]
This is bad.  When I start
```
gdbgui --args cmd arg1 arg2
```
(as of current latest 0.13.1.1) it gets transformed into
```
gdb cmd arg1 arg2 --interpreter=mi2
```
which just cant work.  AFAIK it needs to be
```
gdb --interpreter=mi2 cmd --args arg1 arg2
```

**Comment by jhgoebbert** [comment]
I can confirm, that the "--args" issue is __not__ yet fixed in 0.13.2.0:
Please check https://github.com/cs01/gdbgui/issues/272#issuecomment-538389084

**Comment by cs01** [comment]
Sorry for the inconvenience. If you have the time/ability please submit a PR. Otherwise I will get to it when I can.

**Pull request merged**
