### PR TITLE
Feature/project view

### PR DESCRIPTION
**Pull request by martin-der**
Hello, 
this is the project view.
If the user add a `--project` `/home/me/develop/my-project` parameter to the _backend.py_ command, then the view becomes available on the left.

The displayed name for the project is last folder ( i.e. my-project with this example ).

The view has four buttons. The last one is still a work in progress. It should reveal the current viewed file in the project tree.

Please note that I had to change two import lines in _backend.py_ (l.38 and l.40). It doesn't feel right but I could not start the server without that.

There are issues. 
* The tree is only populated when the source files are fetched ( `source_file_paths` from the store )
* The user can't set the project home folder from the GUI

Hope this will be usable. Let me now what and how I can improve this code.

### CODE REVIEW

**Comment by cs01** [comment]
Thanks for adding this! I have been quite busy lately, but will take a look when I get a chance.

**Comment by martin-der** [comment]
I saw you comment in the pull request : take you time. I fully understand
what lack of time means.

One question : I squashed my commits locally since they where quite messy.
Should I force push the result on my github branch before you review and
maybe accept the pull ? Or is it a bad idea at this point ?
Sorry, this my first pull request and I'm not sure how the result of my
actions will be useful. I don't want to had more work on your side.


2018-01-20 6:18 GMT+01:00 Chad Smith <notifications@github.com>:

**Comment by cs01** [comment]
That is a good question. When I merge the changes, I can either maintain each one of your commits, or I can squash them all into a single commit. I always do the latter, so feel free to push as many commits as you want -- it makes no extra work for me.

Side note: even though you responded via email, it added a comment to the pull request that is publicly visible.

**Comment by cs01** [comment]
I took your changes and worked from them to finish it up. I also added the button to reveal the current file. I put it in a new pull request if you would like to see: https://github.com/cs01/gdbgui/pull/160.

**Pull request closed without merging**
