### PR TITLE
WIP: UI-support for breakpoint conditions

### LINKED ISSUE #185: add conditional breakpoint UI support
Add an input to supply a condition for a breakpoint, and display the condition for the breakpoint if there is one.

Documentation copied below from https://www.sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Breakpoint-Commands.html#GDB_002fMI-Breakpoint-Commands

> The -break-condition Command
Synopsis
 -break-condition number expr
Breakpoint number will stop the program only if the condition in expr is true. The condition becomes part of the ‘-break-list’ output (see the description of the ‘-break-list’ command below).

> GDB Command
The corresponding GDB command is ‘condition’.

> Example
(gdb)
-break-condition 1 1
^done
(gdb)
-break-list
^done,BreakpointTable={nr_rows="1",nr_cols="6",
hdr=[{width="3",alignment="-1",col_name="number",colhdr="Num"},
{width="14",alignment="-1",col_name="type",colhdr="Type"},
{width="4",alignment="-1",col_name="disp",colhdr="Disp"},
{width="3",alignment="-1",col_name="enabled",colhdr="Enb"},
{width="10",alignment="-1",col_name="addr",colhdr="Address"},
{width="40",alignment="2",col_name="what",colhdr="What"}],
body=[bkpt={number="1",type="breakpoint",disp="keep",enabled="y",
addr="0x000100d0",func="main",file="hello.c",fullname="/home/foo/hello.c",
line="5",cond="1",thread-groups=["i1"],times="0",ignore="3"}]}
(gdb)

### PR DESCRIPTION
**Pull request by MatthiasKreileder**
# UI-support for breakpoint conditions

Add a text input field to the Breakpoint component that provides the user the option to specify break conditions.  Closes #185

This is the GUI equivalent to the `(gdb) condition <bkpt_num> <condition>` command.

Here's a screenshot of the UI.  I created one conditional breakpoint via the gdb prompt and then specified a break condition for a second breakpoint that I created via the UI.

conditional_bkpt

## Implementation notes

* Handles the case where the users starts the debugging session over.  E.g. the user types 'run' at the gdb prompt, or clicks on the restart control button in the upper right corner.
* Renders the breakpoint condition in the same style like any other user input (for example the Memory panel's input fields) when the user creates/edits a break condition
* Renders the break condition in grey (as opposed to black) once it has been submitted ("Submitted" as in enter has been hit).
* Treats break conditions set via the gdb prompt gracefully (like conditions submitted via UI).

### How to handle input errors

How should we handle erroneous break conditions?  This change, as is, does not validate the break condition.  It just sends it to the backend. And it seems gdb always (even in the case of error) parrots back the condition as supplied by the frontend.  The console displays an error message in red though, when the breakpoint condition is invalid.  I believe that should be enough to communicate that the condition was not set correctly?

Handling (or shall I say ignoring?!) input errors that way keeps the breakpoint component simple.  And the user can correct the erroneous break condition once she/he sees the error msg in the console.  Let me know if you'd like this to be handled differently.

### What to do about breakpoints with multiple addresses?

I might be overlooking sth but to me it seems as if break conditions on child breakpoints aren't (properly) supported.  E.g. debugging this cpp file

```C++
void print(std::string& s){...}
void print(int i){...}
int main(){
    std::cout << "Hello, overloaded function" << std::endl;
    print("Hello, overloaded function");
    for (int i = 0; i != 100; ++i){
      std::cout << "Hello for the " << i << " th time" << std::endl;
    }
}
```

via the following commands results in an error message.

```
(gdb) b print
(info) info b
1       breakpoint     keep y   <MULTIPLE>         
1.1                         y     0x0000000000000cdc in print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) 
                                                   at func_overload.cpp:6
1.2                         y     0x0000000000000d24 in print(int) at func_overload.cpp:10
(gdb) cond 2.1 num == 50
Bad breakpoint argument: '1.2 num == 50'
```

I am not sure what's the best way to handle this...

Don't care would be one option :P  If, in the example above, the users want to break on line 10 when num is 50 they could simply set an unambiguous breakpoint on line 10 (the line defining `print(int)`) and then set the condition.  Done :)

Alternatively we could do something "clever", like automagically disabling breakpoint 2.1 (that seems to work for child breakpoints) and then inserting an unambiguous breakpoint with the user supplied condition ... Feels a bit hacky though.  Let me know what you would prefer.  I am happy to refactor this PR.

### CODE REVIEW

**Comment by MatthiasKreileder** [comment]
The Travis CI checks have failed :( I had a look at the logs and the failures seem to be unrelated to my change (the job errors out when `webpack` runs).

Please let me know if I am missing sth.

**Comment by cs01** [comment]
> The Travis CI checks have failed :( I had a look at the logs and the failures seem to be unrelated to my change (the job errors out when `webpack` runs).
> 
> Please let me know if I am missing sth.

Hmm yeah it doesn't look related to your change. I unfortunately don't have the time to investigate this at the moment. Did you run similar commands locally to what is run on travis to see if you can reproduce?

I have been wanting to migrate the JS portion of gdbgui to create-react-app, which would fix this, but that is a bigger undertaking.

**Comment by MatthiasKreileder** [comment]
> Hmm yeah it doesn't look related to your change. I unfortunately don't have the time to investigate this at the moment.

To be deadly sure it's unrelated to the change contained in this PR I created a [new dummy PR](https://github.com/cs01/gdbgui/pull/277 ), based off 'dev' that just adds a character to the README?  Also there [all checks failed](https://travis-ci.org/cs01/gdbgui/builds/562686598?utm_source=github_status&utm_medium=notification).  Seems like the CI build is broken.

Would you mind creating a separate issue for fixing the CI checks?  And/or a story to migrate to `create-react-app` (first?)?  I am happy to look into those, but would preferably do that in a separate PR/issue.

> Did you run similar commands locally to what is run on travis to see if you can reproduce?

Truth be told: I am a C++ dev (and gdbgui user obviously :P) and just started to learn about js/react, so I might be missing something but for me, the build instructions in https://www.gdbgui.com/contributing/ never worked.  Is it possible that they are broken in general?  At least for me, they never worked :( I manually installed the dependencies via `npm` and `pip` until I got it working.

**Comment by cs01** [comment]
> Truth be told: I am a C++ dev (and gdbgui user obviously :P) and just started to learn about js/react, so I might be missing something but for me the build instructions in https://www.gdbgui.com/contributing/ never worked. Is it possible that they are broken in general? At least for me, they never worked :( I manually installed the dependencies via npm and pip until I got it working.

Well thanks for jumping in and giving js/React a shot. That is definitely a problem if the contributing instructions don't work! 😕 . I do want to migrate to create-react-app (created https://github.com/cs01/gdbgui/issues/278), but tbh I don't know when I can get to it. I will let you know if I start working on it to keep you in the loop.

**Comment by MatthiasKreileder** [comment]
> I do want to migrate to create-react-app (created #278), but tbh I don't know when I can get to it.

I can look into this if you are fine with that. I know the basics of react/js by now and I am happy to read up on other things I am currently missing. Do you maybe have any pointers on how to get started or what to look into first?

**Comment by cs01** [comment]
Thanks, that's brave of you :) 

Sure, here's some info. First I'd recommend making a small standalone app just to see how it works. https://facebook.github.io/create-react-app/docs/adding-typescript

When you want to try to integrate with gdbgui, the [entry point](https://github.com/cs01/gdbgui/blob/master/webpack.config.js#L5) will have to be used in create-react-app. The output file is currently [build.js](https://github.com/cs01/gdbgui/blob/master/webpack.config.js#L8), which is consumed in the .html file at https://github.com/cs01/gdbgui/blob/master/gdbgui/templates/gdbgui.html#L38.

So those three things (entry point, build file, and html file that consumes build file) will have to be made happy with the new create-react-app.

**Comment by MatthiasKreileder** [comment]
Awesome, thanks!  I'll read up on create-react-app the next days and then start with the instructions you provided.

> that's brave of you :)

Hehe, point taken.  Maybe it'll be too difficult.  Some of my colleagues are good with react though, so I might pick their brain on certain problems whenever I am hopelessly stuck.

**Comment by cs01** [comment]
Either way it will be good experience for you to have. create-react-app is really cool. It can get you up and running quickly. Feel free to chat w/ me more once you get started over in #278.

**Comment by MatthiasKreileder** [comment]
Are you still interested in "UI-support for breakpoint conditions"?  If yes, shall I reopen the PR for this?  Or would you prefer this to be implemented totally differently, and therefore you closed my PR?

I haven't forgotten about the 'create-react-app' migration btw. Whenever I have a bit of spare time I continue with it. But it'll probably still take me two weeks. Still handling the learning curve (:

**Comment by cs01** [comment]
Yes I’m still interested in it. Sorry if I closed this PR prematurely!

Feel free to keep working in this PR or a new one if you prefer, doesn’t matter to me. But you will want to pull in the latest changes from master before you continue.

**Comment by MatthiasKreileder** [comment]
Thanks!  Created a new branch based off the tip of master and cherry-picked my old conditional-bkpt changes: Opened #287

**Pull request closed without merging**
