### PR TITLE
Beautify; bootstrap 4; modernize webpack usage; add keyboard shortcuts; oh my

### PR DESCRIPTION
**Pull request by activedecay**
# todo mvp
1. DONE! ship this! it's beautiful!

# todo nicities (in progress)
 (this is an existing bug) 1. weird visual artifact in threads when args are present in frames, args pop in and out of existence
1. do tooltips the bootstrap way
1. side panel scrolls annoyingly during use 
  (it's the memory or registers tables. 
   refactor to use react and state.)
1. hovervar action that adds expression automatically
1. new setting for memory width in bytes (8, but could be nicer as 16)
1. new settings to remember memory distance from selected address
1. make load binary understand file:/// scheme uris
1. tree thing needs his own window he's annoying as shit to work with
1. register_table_data is 10000 lines long; allow filtering
1. / keymaps to focus load binary input
1. ; keymaps to focus gdb command input 
1. f keymaps to fetch disass -- or do it automatically and as setting? hmm?
1. stylize white input backgrounds
1. asm doesn't switch from at&t to intel until you click twice

# fixed
1. re-layout the whole gui top-to-bottom, bootstrap it!
1. the dashboard template is busted after the bootstrap 4 update
1. hovervar is busted after bootstrap 4 update
1. fix scrolling in code window and in gdb console
1. remember collapse state of right sidebar collapse-ers
1. pretty scrollbars
1. pretty dialogs
1. filesystem style with icons to match mime-types
1. l keymaps to load binary
1. nav bars stick on the top
1. footer (nav bar) sticks to the bottom
1. beautiful text (source code pro)
1. fix icons
1. theme bootstrap using bootswatch
1. use node modules to build webpack dependencies
1. smaller icon sizes
1. smaller text
1. scrollbars show in layouts when debugging
1. module doesn't exist error in python not sure why
1. ugly borders everywhere
1. buttons act like buttons
1. divs act like divs
1. spans act like spans
1. remove hovers from important features
1. goto line is pretty
1. remove more horrible horrible animation effects
1. themed dinky windows with disassm in them cuz ugly
1. button group was not rendered right; don't use .hidden
1. row resizer beauty
1. pretty clear debug gdb mi output btn
1. filesystem picker collapses when text is clicked
1. moved settings into menu
1. load last binary shortcut

### CODE REVIEW

**Comment by activedecay** [comment]
please do not merge this yet

**Comment by activedecay** [comment]
this changeset is over 9000!

**Comment by cs01** [comment]
Wow thank you for all the work you put into this. I tested it out and it does look really nice. I especially like the changes to the side panel. This project really is quite big and after I got it all working I never took the time to really smooth out the css, so I think this is a valuable effort.

With that being said, this is not ready to merge. 

* there are numerous regressions
  * source code cannot be scrolled
  * right sidebar cannot be scrolled
  * panels cannot be resized
  * panels on right have unintuitive behavior, including using buttons to toggle visibility of various panels
  * Copy button next to variable does not notify user it was copied
  * Tree icon does not display tree
  * etc
* run `yarn prettier` to autoformat javascript code
* run `black` to autoformat python code

Even if these were all fixed in this PR, there are way too many changes for me to review in this one PR. The best way forward is to make incremental, easily testable changes. That way you know what is in it and I can review it.

You should shoot for no more than 100 lines per PR unless you cannot make the change in less lines.

I would suggest creating a sequence of PRs, something like
* Cleanup/code quality changes
* Migrate to font awesome instead of glyphs
* Migrate to bootstrap 4 but leave all styling the same (to ensure no regressions and easy testability)
* Improve css for a single component
* Repeat for another component until all components have been improved
* etc

**Comment by activedecay** [comment]
> there are numerous regressions

yes, indeed. i'm glad you took the time to test it for me. which browser are you using?

> source code cannot be scrolled

i assume this is a browser issue. i'll look into using a different library. gemini scrollbars is kinda not the best. i may roll my own.

> right sidebar cannot be scrolled

does this look like the same bug as the source code scroll issue? they both use the gemini thing.

> panels cannot be resized

to be honest, i can live without resizing because i have such wide monitors. i'll be fixing this posthaste by adding a different resize lib. i found a nice last night, but it was too late to start implementing it.

> panels on right have unintuitive behavior, including using buttons to toggle visibility of various panels

fixed in my latest. if you want to pull from https://github.com/activedecay/gdbgui and check the master branch (which was the beautify branch on here) it should make more sense now

> Copy button next to variable does not notify user it was copied

this will only take a moment to fix and will be in the next patch. i think i'll use the popovers or the tooltips.

> Tree icon does not display tree

interesting. i could see the tree fine when i use the hello_c.a example binary. so, you click the tree and it doesn't do what exactly? should it scroll to the tree? i'll check this against the previous behavior before my changes. 

> etc

ya there were a lot of regressions, but overall, i think that the beauty of the thing would overcome that. i didn't think the features that i broke were as numerous as you found, so i deleted the branch. 

> run yarn prettier to autoformat javascript code
> run black to autoformat python code

sure thing. formatting is important to me as well.

---

as far as splitting goes, there's not a chance i'm going to split out 9000 lines of changes by 100-line pull requests. they're already in separate commits, so i was hoping that you'd just follow those. i'll maintain my source fork and pull from your master as you make changes to your fork. when the time comes, maybe we can merge. 

i know that's a terrible way to work together, but i'm hard to work with. sorry.

**Comment by cs01** [comment]
>  which browser are you using?

Chrome

> does this look like the same bug as the source code scroll issue? 

Yes, and I don't think the terminal worked either

> you click the tree and it doesn't do what exactly?

Nothing happened when I clicked it

**Pull request closed without merging**
